In [9]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import ollama

In [4]:
from warnings import simplefilter
simplefilter(action="ignore", category=pd.errors.PerformanceWarning)

In [43]:
df = pd.read_csv('responses.csv')

In [15]:
response = ollama.chat(model='codellama:7b', messages=[
  {
    'role': 'user',
    'content': 'Generate code for outlier detection in python. Dataframe is named df. Attribute is named Height.',
  },
])
print(response['message']['content'])

2024-09-15 20:09:36 [INFO] HTTP Request: POST http://127.0.0.1:11434/api/chat "HTTP/1.1 200 OK"

There are several ways to detect outliers in a dataset, but one common method is to use a statistical method such as z-score or Modified Z-score. Here's an example of how you can implement this method using Python and the pandas library:
```
import pandas as pd

# Load the data into a pandas dataframe
df = pd.read_csv('data.csv')

# Calculate the z-score for each row in the dataset
z_scores = abs(df['Height'] - df['Height'].mean()) / df['Height'].std()

# Determine which rows have a z-score greater than 3 as outliers
outliers = df[z_scores > 3]

print('Outliers:')
print(outliers)
```
This code assumes that the height data is stored in a column named 'Height' in a pandas dataframe called 'df'. The z-score for each row is calculated using the formula: z = (x - mean) / std, where x is the value of the height variable, mean is the mean of the height variable, and std is the standard deviation of the height variable. The absolute value of the z-score is then used to determine whether each row is an outlier.

It's important to note that this is just one example of how you can detect outliers in a dataset using Python. There are many other methods and techniques you can use, depending on your specific needs and the characteristics of your data.

In [19]:
import pandas as pd

# Load the data into a pandas dataframe
df = pd.read_csv('responses.csv')

# Calculate the z-score for each row in the dataset
z_scores = abs(df['Height'] - df['Height'].mean()) / df['Height'].std()

# Determine which rows have a z-score greater than 3 as outliers
outliers = df[z_scores > 3]

print('Outliers:')
outliers

Outliers:

,Music,Slow songs or fast songs,Dance,Folk,Country,Classical music,Musical,Pop,Rock,Metal or Hardrock,...,Age,Height,Weight,Number of siblings,Gender,Left - right handed,Education,Only child,Village - town,House - block of flats
676,5.0,4.0,2.0,2.0,1.0,2.0,2.0,1.0,2.0,2.0,...,20.0,62.0,55.0,2.0,female,right handed,college/bachelor degree,no,city,house/bungalow

In [11]:
response = ollama.chat(model='codellama:7b', messages=[
  {
    'role': 'user',
    'content': 'Generate code for outlier detection with IQR method in python. Dataframe is named df. Attribute is named Height.',
  },
])
print(response['message']['content'])

```
import pandas as pd
from sklearn.metrics import iqr

# Calculate the Interquartile Range (IQR) of the height variable
iqr_height = iqr(df['Height'])

# Calculate the lower and upper boundaries of the IQR
lower_boundary = df['Height'] - 1.5 * iqr_height
upper_boundary = df['Height'] + 1.5 * iqr_height

# Identify outliers using the lower and upper boundaries
outliers = df[~((df['Height'] >= lower_boundary) & (df['Height'] <= upper_boundary))]
```
This code first imports the required libraries, then calculates the Interquartile Range (IQR) of the height variable using the `iqr()` function from scikit-learn. It then calculates the lower and upper boundaries of the IQR as 1.5 times the IQR above and below the median of the height variable, respectively. Finally, it uses these boundaries to identify outliers in the data using the `~` operator to create a mask that selects rows where the height is not within the boundaries.

This method is more robust than using fixed thresholds as the IQR can be used to detect outliers for different ranges of values and it also provides a better understanding of the distribution of the data.

In [13]:
from sklearn.metrics import iqr

# Calculate the Interquartile Range (IQR) of the height variable
iqr_height = iqr(df['Height'])

# Calculate the lower and upper boundaries of the IQR
lower_boundary = df['Height'] - 1.5 * iqr_height
upper_boundary = df['Height'] + 1.5 * iqr_height

# Identify outliers using the lower and upper boundaries
outliers = df[~((df['Height'] >= lower_boundary) & (df['Height'] <= upper_boundary))]

ImportError: cannot import name 'iqr' from 'sklearn.metrics' (C:\Users\kocha\anaconda3\Lib\site-packages\sklearn\metrics\__init__.py)

In [15]:
response = ollama.chat(model='mistral', messages=[
  {
    'role': 'user',
    'content': 'Generate code for outlier detection with IQR method in python. Dataframe is named df. Attribute is named Height.',
  },
])
print(response['message']['content'])

 Here's a Python code snippet that demonstrates the Interquartile Range (IQR) method for outlier detection on a DataFrame column called 'Height'.

```python
import numpy as np
import pandas as pd

# Assuming df is your dataframe and Height is the column name you want to analyze.
q1 = df['Height'].quantile(0.25)
q3 = df['Height'].quantile(0.75)
IQR = q3 - q1
lower_bound = q1 - 1.5 * IQR
upper_bound = q3 + 1.5 * IQR
outliers = df[ (df['Height'] < lower_bound) | (df['Height'] > upper_bound) ]
print("Outliers for Height:")
print(outliers)
```

This code first computes the 1st quartile (Q1) and the 3rd quartile (Q3), then calculates the Interquartile Range (IQR). After that, it defines lower and upper bounds by subtracting and adding 1.5 * IQR respectively to Q1 and Q3. Finally, it identifies any rows in the DataFrame where 'Height' values are below the lower bound or above the upper bound as outliers and prints them.

In [24]:
import numpy as np
import pandas as pd

# Assuming df is your dataframe and Height is the column name you want to analyze.
q1 = df['Height'].quantile(0.25)
q3 = df['Height'].quantile(0.75)
IQR = q3 - q1
lower_bound = q1 - 1.5 * IQR
upper_bound = q3 + 1.5 * IQR
outliers = df[ (df['Height'] < lower_bound) | (df['Height'] > upper_bound) ]
print("Outliers for Height:")
outliers

Outliers for Height:

,Music,Slow songs or fast songs,Dance,Folk,Country,Classical music,Musical,Pop,Rock,Metal or Hardrock,...,Age,Height,Weight,Number of siblings,Gender,Left - right handed,Education,Only child,Village - town,House - block of flats
97,5.0,3.0,2.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,...,19.0,200.0,75.0,1.0,male,right handed,primary school,no,village,block of flats
220,5.0,3.0,4.0,3.0,3.0,4.0,2.0,1.0,3.0,1.0,...,18.0,200.0,90.0,2.0,male,right handed,secondary school,no,village,house/bungalow
547,5.0,4.0,1.0,4.0,2.0,5.0,3.0,1.0,4.0,5.0,...,21.0,203.0,80.0,2.0,male,left handed,secondary school,no,village,house/bungalow
676,5.0,4.0,2.0,2.0,1.0,2.0,2.0,1.0,2.0,2.0,...,20.0,62.0,55.0,2.0,female,right handed,college/bachelor degree,no,city,house/bungalow
799,5.0,3.0,1.0,2.0,3.0,4.0,5.0,2.0,4.0,5.0,...,18.0,203.0,89.0,2.0,male,right handed,secondary school,yes,city,block of flats
992,4.0,4.0,4.0,1.0,4.0,4.0,1.0,3.0,4.0,4.0,...,30.0,200.0,150.0,1.0,male,right handed,masters degree,no,city,block of flats

In [35]:
response = ollama.chat(model='llama3', messages=[
  {
    'role': 'user',
    'content': 'Generate code for outlier detection with IsolationForest method in python. Dataframe is named df. Select the following attributes Height, Weigth and Age.',
  },
])
print(response['message']['content'])

Here's a Python script using the Isolation Forest algorithm for outlier detection on a pandas DataFrame `df`. The script will select the columns 'Height', 'Weigth' and 'Age' for analysis.

```Python
import pandas as pd
from sklearn.ensemble import IsolationForest
from sklearn.preprocessing import StandardScaler

# Select the attributes of interest
attributes = ['Height', 'Weight', 'Age']
X = df[attributes]

# Scale the data
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Train an Isolation Forest model
model = IsolationForest(contamination=0.1)
model.fit(X_scaled)

# Use the model to predict outliers in the test set
y_pred = model.predict(X_scaled)

# Create a new DataFrame with outliers marked as 1, others as -1
outliers_df = pd.DataFrame(y_pred, columns=['Is_Outlier'])
df_with_outliers = pd.concat([df.drop(attributes, axis=1), outliers_df], axis=1)

print(df_with_outliers)
```

In this script:

- We select the attributes 'Height', 'Weight' and 'Age' from our DataFrame `df`.
- We scale the selected data using `StandardScaler` to ensure that all features are on the same scale.
- We train an Isolation Forest model with a contamination rate of 0.1 (i.e., we expect about 10% of the data points to be outliers).
- We use this trained model to predict which data points in our training set are outliers.
- Finally, we create a new DataFrame that includes the predictions from the Isolation Forest model.

The `contamination` parameter in the `IsolationForest` constructor controls how many samples are considered anomalies. The value should be between 0 and 1.

In [51]:
df = df.fillna(df.mean())

C:\Users\kocha\AppData\Local\Temp\ipykernel_30788\114435927.py:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df = df.fillna(df.mean())

In [53]:
df.isnull().sum()

Music                       0
Slow songs or fast songs    0
Dance                       0
Folk                        0
Country                     0
                           ..
Left - right handed         3
Education                   1
Only child                  2
Village - town              4
House - block of flats      4
Length: 150, dtype: int64

In [87]:
import pandas as pd
from sklearn.ensemble import IsolationForest
from sklearn.preprocessing import StandardScaler

# Select the attributes of interest
attributes = ['Height', 'Weight', 'Age']
X = df[attributes]

# Scale the data
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Train an Isolation Forest model
model = IsolationForest(contamination=0.01)
model.fit(X_scaled)

# Use the model to predict outliers in the test set
y_pred = model.predict(X_scaled)

# Create a new DataFrame with outliers marked as 1, others as -1
outliers_df = pd.DataFrame(y_pred, columns=['Is_Outlier'])
#df_with_outliers = pd.concat([df.drop(attributes, axis=1), outliers_df], axis=1)
df_with_outliers = pd.concat([df, outliers_df], axis=1)

df_with_outliers[df_with_outliers['Is_Outlier']==-1][attributes]

         Height  Weight   Age
222  153.000000    42.0  24.0
392  160.000000    47.0  30.0
461  189.000000    96.0  29.0
715  183.000000   111.0  29.0
793  185.000000   120.0  24.0
796  189.000000   113.0  27.0
859  190.000000   125.0  20.0
885  173.514141   165.0  23.0
990  180.000000    93.0  29.0
992  200.000000   150.0  30.0
998  192.000000   105.0  28.0